"""
WhatsApp integration using Twilio WhatsApp API.
"""

from datetime import datetime
from typing import Any, Dict, Optional

from app.utils.config import settings
from app.utils.logger import get_logger

logger = get_logger(__name__)


class WhatsAppIntegration:
    """WhatsApp integration using Twilio."""

    def __init__(self):
        self.account_sid = getattr(settings, "TWILIO_ACCOUNT_SID", "")
        self.auth_token = getattr(settings, "TWILIO_AUTH_TOKEN", "")
        self.whatsapp_number = getattr(settings, "TWILIO_WHATSAPP_NUMBER", "")
        self.client = None

        self._initialize_client()

    def _initialize_client(self):
        """Initialize Twilio client."""
        try:
            if self.account_sid and self.auth_token:
                from twilio.rest import Client

                self.client = Client(self.account_sid, self.auth_token)
                logger.info("Twilio WhatsApp client initialized")
        except ImportError:
            logger.warning("Twilio package not installed")
        except Exception as e:
            logger.error(f"Failed to initialize Twilio: {str(e)}")

    async def send_message(
        self,
        to_number: str,
        message: str,
        media_url: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Send a WhatsApp message."""
        if not self.client:
            return {"success": False, "message": "WhatsApp service not configured"}

        try:
            from_number = f"whatsapp:{self.whatsapp_number}"
            if not to_number.startswith("whatsapp:"):
                to_number = f"whatsapp:{to_number}"

            kwargs = {
                "body": message,
                "from_": from_number,
                "to": to_number,
            }

            if media_url:
                kwargs["media_url"] = [media_url]

            msg = self.client.messages.create(**kwargs)

            logger.info(f"WhatsApp message sent to {to_number}, SID: {msg.sid}")

            return {
                "success": True,
                "message_sid": msg.sid,
                "status": msg.status,
                "timestamp": datetime.utcnow().isoformat(),
            }

        except Exception as e:
            logger.error(f"Failed to send WhatsApp message: {str(e)}")
            return {
                "success": False,
                "message": f"Failed to send WhatsApp message: {str(e)}",
                "timestamp": datetime.utcnow().isoformat(),
            }

    async def send_reminder(self, to_number: str, reminder_data: Dict[str, Any]) -> Dict[str, Any]:
        """Send a formatted reminder via WhatsApp."""
        message = f"""
📅 *Reminder from Mew*

*{reminder_data.get("title", "Untitled")}*

⏰ Time: {reminder_data.get("time", "Not specified")}
📝 Details: {reminder_data.get("details", "No details")}
        """.strip()

        return await self.send_message(to_number, message)

    async def send_summary(self, to_number: str, summary_data: Dict[str, Any]) -> Dict[str, Any]:
        """Send a daily summary via WhatsApp."""
        message = f"""
📊 *Daily Summary*

📅 Date: {summary_data.get("date", "Today")}

{summary_data.get("content", "No activities")}

Generated by Mew Assistant 🐱
        """.strip()

        return await self.send_message(to_number, message)

    def parse_incoming_message(self, webhook_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Normalise a Twilio incoming-WhatsApp webhook payload.

        Twilio prefixes WhatsApp numbers with "whatsapp:" (e.g.
        "whatsapp:+14155551234"); callers elsewhere in the app want the
        bare phone number like every other channel, so that prefix is
        stripped here rather than leaking into the rest of the pipeline.
        """
        from_number = webhook_data.get("From", "")
        if from_number.startswith("whatsapp:"):
            from_number = from_number[len("whatsapp:") :]

        return {
            "message_sid": webhook_data.get("MessageSid", ""),
            "from_number": from_number,
            "to_number": webhook_data.get("To", ""),
            "body": webhook_data.get("Body", ""),
            "num_media": int(webhook_data.get("NumMedia") or 0),
            "profile_name": webhook_data.get("ProfileName") or None,
        }
